### ISSUE TITLE
mac os has invalid geth path

### ISSUE THREAD

**Issue by splix** [ethereumproject/mist#11]
#### System information

```
Version: `0.8.1`
OS & Version: osx
Node type: `(default)`
```

Error:

```
[2016-08-04 18:26:52.947] [ERROR] EthereumNode - Failed to start node { Error: spawn /Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth',
  path: '/Applications/Ethereum-Wallet.app/Contents/Frameworks/node/geth/geth',
  spawnargs: [ '--fast', '--cache', '512' ] }
```

But this dir contains only `eth/eth` in this dir (which is correct go-ethereum v1.4.10)

**Comment by realcodywburns** [comment]
same fault as in the windows build. try copying the /eth/eth folder and renaming it geth/geth   Mist defaults into geth but doesn't really seem to care if its using the program only the path. geth needs to be added, but the band-aid should get it you up for further testing

**Comment by whatisgravity** [comment]
Just tested this, I will have a patch ready for the build script soon.

I will update the OSX build to reflect this this change. It launched after that change in my osx test env but I will still need to sign the package with the key we obtained.

**Comment by whatisgravity** [comment]
The binary has been fixed. Reopen if there are other related issues.
