### ISSUE TITLE
It does not connect to peers

### ISSUE THREAD

**Issue by onedal** [ethereumproject/mist#34]
```
➜  Ethereum-Wallet-linux64-0-8-1 ./Ethereum-Wallet
[2016-12-24 22:40:46.430] [INFO] main - Running in production mode: true
[2016-12-24 22:40:46.508] [INFO] main - Starting in Wallet mode
[2016-12-24 22:40:46.727] [INFO] Db - Loading db: /home/alex/.config/Mist/mist.lokidb
[2016-12-24 22:40:46.736] [INFO] Windows - Creating commonly-used windows
[2016-12-24 22:40:46.737] [INFO] Windows - Create secondary window: loading, owner: notset
[2016-12-24 22:40:46.769] [INFO] updateChecker - Check for update...
[2016-12-24 22:40:48.931] [INFO] Windows - Create primary window: main, owner: notset
[2016-12-24 22:40:48.956] [INFO] Windows - Create primary window: splash, owner: notset
[2016-12-24 22:40:49.285] [INFO] ipcCommunicator - Backend language set to:  ru
[2016-12-24 22:40:49.924] [INFO] (ui: splash) - Web3 already initialized, re-using provider.
[2016-12-24 22:40:50.169] [INFO] Sockets/node-ipc - Connect to {"path":"/home/alex/.ethereum/geth.ipc"}
[2016-12-24 22:40:50.175] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-12-24 22:40:51.178] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-12-24 22:40:52.181] [WARN] Sockets/node-ipc - Connection failed, retrying after 1000ms...
[2016-12-24 22:40:52.742] [ERROR] updateChecker - Error checking for update TypeError: Invalid Version: v0.9.1pre
    at new SemVer (/run/media/alex/8b99e7b1-8026-44eb-9148-35347314e23c/Ethereum-Wallet-linux64-0-8-1/resources/app.asar/node_modules/semver/semver.js:293:11)
    at compare (/run/media/alex/8b99e7b1-8026-44eb-9148-35347314e23c/Ethereum-Wallet-linux64-0-8-1/resources/app.asar/node_modules/semver/semver.js:566:10)
    at Function.gt (/run/media/alex/8b99e7b1-8026-44eb-9148-35347314e23c/Ethereum-Wallet-linux64-0-8-1/resources/app.asar/node_modules/semver/semver.js:595:10)
    at got.then (/run/media/alex/8b99e7b1-8026-44eb-9148-35347314e23c/Ethereum-Wallet-linux64-0-8-1/resources/app.asar/modules/updateChecker.js:49:20)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[2016-12-24 22:40:53.174] [ERROR] Sockets/node-ipc - Connection failed (3000ms elapsed)
[2016-12-24 22:40:53.179] [WARN] EthereumNode - Failed to connect to node. Maybe it's not running so let's start our own...
[2016-12-24 22:40:53.181] [INFO] EthereumNode - Node type: geth
[2016-12-24 22:40:53.181] [INFO] EthereumNode - Network: main
[2016-12-24 22:40:53.182] [INFO] EthereumNode - Start node: geth main
[2016-12-24 22:40:56.256] [INFO] EthereumNode - 3000ms elapsed, assuming node started up successfully
[2016-12-24 22:40:56.258] [INFO] EthereumNode - Started node successfully: geth main
[2016-12-24 22:40:56.275] [INFO] Sockets/node-ipc - Connect to {"path":"/home/alex/.ethereum/geth.ipc"}
[2016-12-24 22:40:56.280] [INFO] Sockets/node-ipc - Connected!
[2016-12-24 22:40:56.281] [INFO] NodeSync - Ethereum node connected, re-start sync
[2016-12-24 22:40:56.281] [INFO] NodeSync - Starting sync loop
[2016-12-24 22:40:56.282] [INFO] Sockets/6 - Connect to {"path":"/home/alex/.ethereum/geth.ipc"}
[2016-12-24 22:40:56.283] [INFO] main - Connected via IPC to node.
[2016-12-24 22:40:56.300] [INFO] Sockets/6 - Connected!
[2016-12-24 22:40:56.313] [INFO] (ui: splash) - network is mainnet
```
Looking for peers...

Then you can log in the client, but there is not connected to peers.
How do I connect to peers? Where the file is saved by default wallet.dat???

**Comment by colibry545** [comment]
Unfortunately this version is incompatible with current Ethereum Classic. We don’t have new Linux build yet. 

issue #35
